<?php

use Illuminate\Database\Seeder;

class RecitersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('reciters')->delete();
        
        \DB::table('reciters')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Rizwan Zaidi',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476190002.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 12:46:42',
                'updated_at' => '2016-10-11 12:46:42',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Raza Haider',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476190072.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 12:47:52',
                'updated_at' => '2016-10-11 12:47:52',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Tejani Brothers',
                'description' => '<p>Please check out there site at</p>
<p><a href="http://www.tejanibrothers.com" target="_blank">www.tejanibrothers.com</a></p>',
                'hits' => 0,
                'imagepath' => '1477754774.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:16:36',
                'updated_at' => '2016-10-29 15:26:14',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Abbas Bandali',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192316.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:25:16',
                'updated_at' => '2016-10-11 13:25:16',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Husein Virji',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192360.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:26:00',
                'updated_at' => '2016-10-11 13:26:00',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Irfan Haider',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192416.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:26:56',
                'updated_at' => '2016-10-11 13:26:56',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Shahid Baltistani',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192527.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:28:47',
                'updated_at' => '2016-10-11 13:28:47',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Ali Safdar',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192769.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:32:49',
                'updated_at' => '2016-10-11 13:32:49',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Nadeem Sarwar',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192873.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:34:33',
                'updated_at' => '2016-10-11 13:34:33',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Hassan Sadiq',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192916.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:35:16',
                'updated_at' => '2016-10-11 13:35:16',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Tirmah Zaidi',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476192966.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-11 13:36:06',
                'updated_at' => '2016-10-11 13:36:06',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Batul and Fatima Dhamani',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476352456.gif',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:54:16',
                'updated_at' => '2016-10-13 09:54:16',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Mohammad ali Kazmi',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476352526.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:55:26',
                'updated_at' => '2016-10-13 09:55:26',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Adil Karim',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476352580.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:56:20',
                'updated_at' => '2016-10-13 09:56:20',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Abbas Hussein Pyarali',
                'description' => '<p> .</p>',
                'hits' => 0,
                'imagepath' => '1476352654.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:57:34',
                'updated_at' => '2016-10-13 09:57:34',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Ishtiaq Hussain Diek',
                'description' => '<p>.</p>',
                'hits' => 0,
                'imagepath' => '1476352698.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:58:18',
                'updated_at' => '2016-10-13 09:58:18',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Lakhanie brothers',
                'description' => '<p>..</p>',
                'hits' => 0,
                'imagepath' => '1476352739.gif',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:58:59',
                'updated_at' => '2016-10-13 09:58:59',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Hashim Sisters',
                'description' => '<p>..</p>',
                'hits' => 0,
                'imagepath' => '1476352775.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 09:59:35',
                'updated_at' => '2016-10-13 09:59:35',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Fatemah Ladak',
                'description' => '<p>a</p>',
                'hits' => 0,
                'imagepath' => '1476352810.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:00:10',
                'updated_at' => '2016-10-13 10:00:10',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Abbas Lalji',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476352851.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:00:51',
                'updated_at' => '2016-10-13 10:00:51',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Voices of Passion',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476352926.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:02:06',
                'updated_at' => '2016-10-13 10:02:06',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Murtaza Gulamhusein',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476352976.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:02:56',
                'updated_at' => '2016-10-13 10:02:56',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Sadik Pieraly',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353028.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:03:48',
                'updated_at' => '2016-10-13 10:03:48',
            ),
            23 => 
            array (
                'id' => 24,
            'name' => 'Shujaat Rizvi (Farhan Ali)',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353064.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:04:24',
                'updated_at' => '2016-10-13 10:04:24',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Dast-e-Imamia',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353109.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:05:09',
                'updated_at' => '2016-10-13 10:05:09',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Mir Hassan Mir',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353152.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:05:52',
                'updated_at' => '2016-10-13 10:05:52',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Abbas Kermalli',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353185.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:06:25',
                'updated_at' => '2016-10-13 10:06:25',
            ),
            27 => 
            array (
                'id' => 28,
            'name' => 'Sangat Imam Hassan Askari (AS)',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353243.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:07:23',
                'updated_at' => '2016-10-13 10:07:23',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Mesum Abbas',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353273.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:07:53',
                'updated_at' => '2016-10-13 10:07:53',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Ghazi Sangat',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353302.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:08:22',
                'updated_at' => '2016-10-13 10:08:22',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Muslim Remtulla',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353339.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:08:59',
                'updated_at' => '2016-10-13 10:08:59',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Musayyab Ali Rizvi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353378.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:09:38',
                'updated_at' => '2016-10-13 10:09:38',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Shabih Abbas Jafri',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353410.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:10:10',
                'updated_at' => '2016-10-13 10:10:10',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Quassar Raza',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353448.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:10:48',
                'updated_at' => '2016-10-13 10:10:48',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Ishtiaq Hussain',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353495.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:11:35',
                'updated_at' => '2016-10-13 10:11:35',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Aamir Rizvi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353526.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:12:06',
                'updated_at' => '2016-10-13 10:12:06',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Ali Raza Charania',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353559.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:12:39',
                'updated_at' => '2016-10-13 10:12:39',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Nasir Zaidi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353584.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:13:04',
                'updated_at' => '2016-10-13 10:13:04',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Aslam Hashim',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353612.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:13:32',
                'updated_at' => '2016-10-13 10:13:32',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Hussein Mukhtar',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353642.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:14:02',
                'updated_at' => '2016-10-13 10:14:02',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Naqvi Brothers',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353668.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:14:28',
                'updated_at' => '2016-10-13 10:14:28',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Aamir Baltistani',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353694.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:14:54',
                'updated_at' => '2016-10-13 10:14:54',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Tahsin Kazilbash',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353759.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:15:59',
                'updated_at' => '2016-10-13 10:15:59',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Murtaza Mamdani',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353801.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:16:41',
                'updated_at' => '2016-10-13 10:16:41',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Dast-e-Muhammadi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353833.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:17:13',
                'updated_at' => '2016-10-13 10:17:13',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Sajid Hussain Jaffri',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353867.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:17:47',
                'updated_at' => '2016-10-13 10:17:47',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Alideep Rizvi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353899.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:18:19',
                'updated_at' => '2016-10-13 10:18:19',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Shuja Abbas Zaidpuri',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353926.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:18:46',
                'updated_at' => '2016-10-13 10:18:46',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Mujtaba Haider Naqvi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476353957.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:19:17',
                'updated_at' => '2016-10-13 10:19:17',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Zaigham Hadi',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476354001.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:20:01',
                'updated_at' => '2016-10-13 10:20:01',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Mamod Danis',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476354031.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:20:31',
                'updated_at' => '2016-10-13 10:20:31',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Sadiq Moosa',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476354061.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:21:01',
                'updated_at' => '2016-10-13 10:21:01',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Faraz Hyder Jaffri',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476354117.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:21:57',
                'updated_at' => '2016-10-13 10:21:57',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Jaffer Fazel',
                'description' => '<p>\\</p>',
                'hits' => 0,
                'imagepath' => '1476354151.jpg',
                'status' => 0,
                'moderated_at' => NULL,
                'moderated_by' => NULL,
                'created_at' => '2016-10-13 10:22:31',
                'updated_at' => '2016-10-13 10:22:31',
            ),
        ));
        
        
    }
}
