preset: laravel

risky: false

disabled:
  - concat_without_spaces
  - binary_operator_spaces
  - length_ordered_imports
  - not_operator_with_successor_space

enabled:
  - concat_with_spaces

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
