preset: laravel

risky: false

finder:
  exclude:
    - "tests"
  name:
    - "*.php"

disabled:
  - concat_without_spaces
  - binary_operator_spaces
  - alpha_ordered_imports
enabled:
  - concat_with_spaces
