preset: laravel

risky: false

disabled:
  - concat_without_spaces
  - binary_operator_spaces
  - alpha_ordered_imports

enabled:
  - concat_with_spaces

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
