language: php

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: vendor/bin/phpunit
